$(document).ready(function() {
  // Função para salvar o conteúdo em um arquivo de texto
  function salvarTextoEmArquivo(texto, nomeArquivo) {
    var blob = new Blob([texto], { type: 'text/plain' });
    var link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.download = nomeArquivo;
    link.click();
  }

  // Evento de clique no botão de salvar
  $('#salvarBotao').click(function() {
    var textoASalvar = "";

    //IMPLEMENTAR AQUI A PARTE DE SALVAR
    //textoASalvar += "Input xx: " + $('#ID_DI_OBJETO').val() + "\n";
    textoASalvar += "Input 1: " + $('#nome').val() + "\n";
    textoASalvar += "Input 2: " + $('#jogador').val() + "\n";
    textoASalvar += "Input 3: " + $('#ptotais').val() + "\n";
    textoASalvar += "Input 4: " + $('#ptgastos').val() + "\n";
    textoASalvar += "Input 5: " + $('#ptrestantes').val() + "\n";
    textoASalvar += "Input 6: " + $('#primario1').val() + "\n";
    textoASalvar += "Input 7: " + $('#primario2').val() + "\n";
    textoASalvar += "Input 8: " + $('#primario3').val() + "\n";
    textoASalvar += "Input 9: " + $('#primario4').val() + "\n";
    textoASalvar += "Input 10: " + $('#sec1').val() + "\n";
    textoASalvar += "Input 11: " + $('#sec2').val() + "\n";
    textoASalvar += "Input 12: " + $('#sec3').val() + "\n";
    textoASalvar += "Input 13: " + $('#sec4').val() + "\n";
    textoASalvar += "Input 14: " + $('#sec5').val() + "\n";
    textoASalvar += "Input 15: " + $('#sec6').val() + "\n";

    textoASalvar += "Input 16: " + $('#der1').val() + "\n";
    textoASalvar += "Input 17: " + $('#der2').val() + "\n";
    textoASalvar += "Input 18: " + $('#der3').val() + "\n";
    textoASalvar += "Input 19: " + $('#der4').val() + "\n";
    textoASalvar += "Input 20: " + $('#der5').val() + "\n";

    textoASalvar += "Input 21: " + $('#defesa1').val() + "\n";
    textoASalvar += "Input 22: " + $('#defesa2').val() + "\n";
    textoASalvar += "Input 23: " + $('#defesa3').val() + "\n";
    textoASalvar += "Input 24: " + $('#defesa4').val() + "\n";

    textoASalvar += "Input 25: " + $('#arma1').val() + "\n";
    textoASalvar += "Input 26: " + $('#arma2').val() + "\n";
    textoASalvar += "Input 27: " + $('#arma3').val() + "\n";
    textoASalvar += "Input 28: " + $('#arma4').val() + "\n";
    textoASalvar += "Input 29: " + $('#arma5').val() + "\n";
    textoASalvar += "Input 30: " + $('#arma6').val() + "\n";
    textoASalvar += "Input 31: " + $('#arma7').val() + "\n";
    textoASalvar += "Input 32: " + $('#arma8').val() + "\n";

    textoASalvar += "Input 33: " + $('#arma11').val() + "\n";
textoASalvar += "Input 34: " + $('#arma12').val() + "\n";
textoASalvar += "Input 35: " + $('#arma13').val() + "\n";
textoASalvar += "Input 36: " + $('#arma14').val() + "\n";
textoASalvar += "Input 37: " + $('#arma15').val() + "\n";
textoASalvar += "Input 38: " + $('#arma16').val() + "\n";
textoASalvar += "Input 39: " + $('#arma17').val() + "\n";
textoASalvar += "Input 40: " + $('#arma18').val() + "\n";

textoASalvar += "Input 41: " + $('#arma21').val() + "\n";
textoASalvar += "Input 42: " + $('#arma22').val() + "\n";
textoASalvar += "Input 43: " + $('#arma23').val() + "\n";
textoASalvar += "Input 44: " + $('#arma24').val() + "\n";
textoASalvar += "Input 45: " + $('#arma25').val() + "\n";
textoASalvar += "Input 46: " + $('#arma26').val() + "\n";
textoASalvar += "Input 47: " + $('#arma27').val() + "\n";
textoASalvar += "Input 48: " + $('#arma28').val() + "\n";

textoASalvar += "Input 49: " + $('#arma31').val() + "\n";
textoASalvar += "Input 50: " + $('#arma32').val() + "\n";
textoASalvar += "Input 51: " + $('#arma33').val() + "\n";
textoASalvar += "Input 52: " + $('#arma34').val() + "\n";
textoASalvar += "Input 53: " + $('#arma35').val() + "\n";
textoASalvar += "Input 54: " + $('#arma36').val() + "\n";
textoASalvar += "Input 55: " + $('#arma37').val() + "\n";
textoASalvar += "Input 56: " + $('#arma38').val() + "\n";

textoASalvar += "Input 57: " + $('#vantagens1').val() + "\n";
textoASalvar += "Input 58: " + $('#vantagens2').val() + "\n";
textoASalvar += "Input 59: " + $('#vantagens3').val() + "\n";
textoASalvar += "Input 60: " + $('#vantagens4').val() + "\n";
textoASalvar += "Input 61: " + $('#vantagens5').val() + "\n";
textoASalvar += "Input 62: " + $('#vantagens6').val() + "\n";
textoASalvar += "Input 63: " + $('#vantagens7').val() + "\n";
textoASalvar += "Input 64: " + $('#vantagens8').val() + "\n";
textoASalvar += "Input 65: " + $('#vantagens9').val() + "\n";
textoASalvar += "Input 66: " + $('#vantagens10').val() + "\n";
textoASalvar += "Input 67: " + $('#vantagens11').val() + "\n";
textoASalvar += "Input 68: " + $('#vantagens12').val() + "\n";
textoASalvar += "Input 69: " + $('#vantagens13').val() + "\n";
textoASalvar += "Input 70: " + $('#vantagens14').val() + "\n";
textoASalvar += "Input 71: " + $('#vantagens15').val() + "\n";
textoASalvar += "Input 72: " + $('#vantagens16').val() + "\n";
textoASalvar += "Input 73: " + $('#vantagens17').val() + "\n";
textoASalvar += "Input 74: " + $('#vantagens18').val() + "\n";
textoASalvar += "Input 75: " + $('#vantagens19').val() + "\n";
textoASalvar += "Input 76: " + $('#vantagens20').val() + "\n";

textoASalvar += "Input 77: " + $('#desvantagens1').val() + "\n";
textoASalvar += "Input 78: " + $('#desvantagens2').val() + "\n";
textoASalvar += "Input 79: " + $('#desvantagens3').val() + "\n";
textoASalvar += "Input 80: " + $('#desvantagens4').val() + "\n";
textoASalvar += "Input 81: " + $('#desvantagens5').val() + "\n";
textoASalvar += "Input 82: " + $('#desvantagens6').val() + "\n";
textoASalvar += "Input 83: " + $('#desvantagens7').val() + "\n";
textoASalvar += "Input 84: " + $('#desvantagens8').val() + "\n";
textoASalvar += "Input 85: " + $('#desvantagens9').val() + "\n";
textoASalvar += "Input 86: " + $('#desvantagens10').val() + "\n";
textoASalvar += "Input 87: " + $('#desvantagens11').val() + "\n";
textoASalvar += "Input 88: " + $('#desvantagens12').val() + "\n";
textoASalvar += "Input 89: " + $('#desvantagens13').val() + "\n";
textoASalvar += "Input 90: " + $('#desvantagens14').val() + "\n";
textoASalvar += "Input 91: " + $('#desvantagens15').val() + "\n";
textoASalvar += "Input 92: " + $('#desvantagens16').val() + "\n";
textoASalvar += "Input 93: " + $('#desvantagens17').val() + "\n";
textoASalvar += "Input 94: " + $('#desvantagens18').val() + "\n";
textoASalvar += "Input 95: " + $('#desvantagens19').val() + "\n";
textoASalvar += "Input 96: " + $('#desvantagens20').val() + "\n";

textoASalvar += "Input 97: " + $('#skills1').val() + "\n";
textoASalvar += "Input 98: " + $('#skills2').val() + "\n";
textoASalvar += "Input 99: " + $('#skills3').val() + "\n";
textoASalvar += "Input 100: " + $('#skills4').val() + "\n";
textoASalvar += "Input 101: " + $('#skills5').val() + "\n";
textoASalvar += "Input 102: " + $('#skills6').val() + "\n";
textoASalvar += "Input 103: " + $('#skills7').val() + "\n";
textoASalvar += "Input 104: " + $('#skills8').val() + "\n";
textoASalvar += "Input 105: " + $('#skills9').val() + "\n";
textoASalvar += "Input 106: " + $('#skills10').val() + "\n";
textoASalvar += "Input 107: " + $('#skills11').val() + "\n";
textoASalvar += "Input 108: " + $('#skills12').val() + "\n";
textoASalvar += "Input 109: " + $('#skills13').val() + "\n";
textoASalvar += "Input 110: " + $('#skills14').val() + "\n";
textoASalvar += "Input 111: " + $('#skills15').val() + "\n";
textoASalvar += "Input 112: " + $('#skills16').val() + "\n";
textoASalvar += "Input 113: " + $('#skills17').val() + "\n";
textoASalvar += "Input 114: " + $('#skills18').val() + "\n";
textoASalvar += "Input 115: " + $('#skills19').val() + "\n";
textoASalvar += "Input 116: " + $('#skills20').val() + "\n";
textoASalvar += "Input 117: " + $('#skills21').val() + "\n";
textoASalvar += "Input 118: " + $('#skills22').val() + "\n";
textoASalvar += "Input 119: " + $('#skills23').val() + "\n";
textoASalvar += "Input 120: " + $('#skills24').val() + "\n";
textoASalvar += "Input 121: " + $('#skills25').val() + "\n";
textoASalvar += "Input 122: " + $('#skills26').val() + "\n";
textoASalvar += "Input 123: " + $('#skills27').val() + "\n";
textoASalvar += "Input 124: " + $('#skills28').val() + "\n";
textoASalvar += "Input 125: " + $('#skills29').val() + "\n";
textoASalvar += "Input 126: " + $('#skills30').val() + "\n";
textoASalvar += "Input 127: " + $('#skills31').val() + "\n";
textoASalvar += "Input 128: " + $('#skills32').val() + "\n";
textoASalvar += "Input 129: " + $('#skills33').val() + "\n";
textoASalvar += "Input 130: " + $('#skills34').val() + "\n";
textoASalvar += "Input 131: " + $('#skills35').val() + "\n";
textoASalvar += "Input 132: " + $('#skills36').val() + "\n";
textoASalvar += "Input 133: " + $('#skills37').val() + "\n";
textoASalvar += "Input 134: " + $('#skills38').val() + "\n";
textoASalvar += "Input 135: " + $('#skills39').val() + "\n";
textoASalvar += "Input 136: " + $('#skills40').val() + "\n";

textoASalvar += "Input 137: " + $('#skillsx1').val() + "\n";
textoASalvar += "Input 138: " + $('#skillsx2').val() + "\n";
textoASalvar += "Input 139: " + $('#skillsx3').val() + "\n";
textoASalvar += "Input 140: " + $('#skillsx4').val() + "\n";
textoASalvar += "Input 141: " + $('#skillsx5').val() + "\n";
textoASalvar += "Input 142: " + $('#skillsx6').val() + "\n";
textoASalvar += "Input 143: " + $('#skillsx7').val() + "\n";
textoASalvar += "Input 144: " + $('#skillsx8').val() + "\n";
textoASalvar += "Input 145: " + $('#skillsx9').val() + "\n";
textoASalvar += "Input 146: " + $('#skillsx10').val() + "\n";
textoASalvar += "Input 147: " + $('#skillsx11').val() + "\n";
textoASalvar += "Input 148: " + $('#skillsx12').val() + "\n";
textoASalvar += "Input 149: " + $('#skillsx13').val() + "\n";
textoASalvar += "Input 150: " + $('#skillsx14').val() + "\n";
textoASalvar += "Input 151: " + $('#skillsx15').val() + "\n";
textoASalvar += "Input 152: " + $('#skillsx16').val() + "\n";
textoASalvar += "Input 153: " + $('#skillsx17').val() + "\n";
textoASalvar += "Input 154: " + $('#skillsx18').val() + "\n";
textoASalvar += "Input 155: " + $('#skillsx19').val() + "\n";
textoASalvar += "Input 156: " + $('#skillsx20').val() + "\n";
textoASalvar += "Input 157: " + $('#skillsx21').val() + "\n";
textoASalvar += "Input 158: " + $('#skillsx22').val() + "\n";
textoASalvar += "Input 159: " + $('#skillsx23').val() + "\n";
textoASalvar += "Input 160: " + $('#skillsx24').val() + "\n";
textoASalvar += "Input 161: " + $('#skillsx25').val() + "\n";
textoASalvar += "Input 162: " + $('#skillsx26').val() + "\n";
textoASalvar += "Input 163: " + $('#skillsx27').val() + "\n";
textoASalvar += "Input 164: " + $('#skillsx28').val() + "\n";
textoASalvar += "Input 165: " + $('#skillsx29').val() + "\n";
textoASalvar += "Input 166: " + $('#skillsx30').val() + "\n";
textoASalvar += "Input 167: " + $('#skillsx31').val() + "\n";
textoASalvar += "Input 168: " + $('#skillsx32').val() + "\n";
textoASalvar += "Input 169: " + $('#skillsx33').val() + "\n";
textoASalvar += "Input 170: " + $('#skillsx34').val() + "\n";
textoASalvar += "Input 171: " + $('#skillsx35').val() + "\n";
textoASalvar += "Input 172: " + $('#skillsx36').val() + "\n";
textoASalvar += "Input 173: " + $('#skillsx37').val() + "\n";
textoASalvar += "Input 174: " + $('#skillsx38').val() + "\n";
textoASalvar += "Input 175: " + $('#skillsx39').val() + "\n";
textoASalvar += "Input 176: " + $('#skillsx40').val() + "\n";

textoASalvar += "Input 177: " + $('#skillsxx1').val() + "\n";
textoASalvar += "Input 178: " + $('#skillsxx2').val() + "\n";
textoASalvar += "Input 179: " + $('#skillsxx3').val() + "\n";
textoASalvar += "Input 180: " + $('#skillsxx4').val() + "\n";
textoASalvar += "Input 181: " + $('#skillsxx5').val() + "\n";
textoASalvar += "Input 182: " + $('#skillsxx6').val() + "\n";
textoASalvar += "Input 183: " + $('#skillsxx7').val() + "\n";
textoASalvar += "Input 184: " + $('#skillsxx8').val() + "\n";
textoASalvar += "Input 185: " + $('#skillsxx9').val() + "\n";
textoASalvar += "Input 186: " + $('#skillsxx10').val() + "\n";
textoASalvar += "Input 187: " + $('#skillsxx11').val() + "\n";
textoASalvar += "Input 188: " + $('#skillsxx12').val() + "\n";
textoASalvar += "Input 189: " + $('#skillsxx13').val() + "\n";
textoASalvar += "Input 190: " + $('#skillsxx14').val() + "\n";
textoASalvar += "Input 191: " + $('#skillsxx15').val() + "\n";
textoASalvar += "Input 192: " + $('#skillsxx16').val() + "\n";
textoASalvar += "Input 193: " + $('#skillsxx17').val() + "\n";
textoASalvar += "Input 194: " + $('#skillsxx18').val() + "\n";
textoASalvar += "Input 195: " + $('#skillsxx19').val() + "\n";
textoASalvar += "Input 196: " + $('#skillsxx20').val() + "\n";
textoASalvar += "Input 197: " + $('#skillsxx21').val() + "\n";
textoASalvar += "Input 198: " + $('#skillsxx22').val() + "\n";
textoASalvar += "Input 199: " + $('#skillsxx23').val() + "\n";
textoASalvar += "Input 200: " + $('#skillsxx24').val() + "\n";
textoASalvar += "Input 201: " + $('#skillsxx25').val() + "\n";
textoASalvar += "Input 202: " + $('#skillsxx26').val() + "\n";
textoASalvar += "Input 203: " + $('#skillsxx27').val() + "\n";
textoASalvar += "Input 204: " + $('#skillsxx28').val() + "\n";
textoASalvar += "Input 205: " + $('#skillsxx29').val() + "\n";
textoASalvar += "Input 206: " + $('#skillsxx30').val() + "\n";
textoASalvar += "Input 207: " + $('#skillsxx31').val() + "\n";
textoASalvar += "Input 208: " + $('#skillsxx32').val() + "\n";
textoASalvar += "Input 209: " + $('#skillsxx33').val() + "\n";
textoASalvar += "Input 210: " + $('#skillsxx34').val() + "\n";
textoASalvar += "Input 211: " + $('#skillsxx35').val() + "\n";
textoASalvar += "Input 212: " + $('#skillsxx36').val() + "\n";
textoASalvar += "Input 213: " + $('#skillsxx37').val() + "\n";
textoASalvar += "Input 214: " + $('#skillsxx38').val() + "\n";
textoASalvar += "Input 215: " + $('#skillsxx39').val() + "\n";
textoASalvar += "Input 216: " + $('#skillsxx40').val() + "\n";

textoASalvar += "Input 217: " + $('#textarea1').val() + "\n";

    var nomeDoArquivo = "ficha.txt";
    salvarTextoEmArquivo(textoASalvar, nomeDoArquivo);
  });

  // Evento de clique no botão de carregar
  $('#carregarBotao').click(function() {
    $('#carregarArquivo').click();
  });

  // Evento quando um arquivo é selecionado
  $('#carregarArquivo').change(function(event) {
    var arquivo = event.target.files[0];
    var leitor = new FileReader();
    leitor.onload = function(e) {
      var conteudo = e.target.result;
      var inputs = conteudo.split('\n');


      //IMPLEMENTAR AQUI A PARTE DE CARREGAR
     // $('#ID_DO_OBJETO').val(inputs[INPUT_CORRESPONDENTE].split(': ')[1].trim());
      $('#nome').val(inputs[0].split(': ')[1].trim());
      $('#jogador').val(inputs[1].split(': ')[1].trim());

      $('#ptotais').val(inputs[2].split(': ')[1].trim());
      $('#ptgastos').val(inputs[3].split(': ')[1].trim());
      $('#ptrestantes').val(inputs[4].split(': ')[1].trim());

      $('#primario1').val(inputs[4+1].split(': ')[1].trim());
$('#primario2').val(inputs[5+1].split(': ')[1].trim());
$('#primario3').val(inputs[6+1].split(': ')[1].trim());
$('#primario4').val(inputs[7+1].split(': ')[1].trim());

$('#sec1').val(inputs[8+1].split(': ')[1].trim());
$('#sec2').val(inputs[9+1].split(': ')[1].trim());
$('#sec3').val(inputs[10+1].split(': ')[1].trim());
$('#sec4').val(inputs[11+1].split(': ')[1].trim());
$('#sec5').val(inputs[12+1].split(': ')[1].trim());
$('#sec6').val(inputs[13+1].split(': ')[1].trim());

$('#der1').val(inputs[14+1].split(': ')[1].trim());
$('#der2').val(inputs[15+1].split(': ')[1].trim());
$('#der3').val(inputs[16+1].split(': ')[1].trim());
$('#der4').val(inputs[17+1].split(': ')[1].trim());
$('#der5').val(inputs[18+1].split(': ')[1].trim());

$('#defesa1').val(inputs[19+1].split(': ')[1].trim());
$('#defesa2').val(inputs[20+1].split(': ')[1].trim());
$('#defesa3').val(inputs[21+1].split(': ')[1].trim());
$('#defesa4').val(inputs[22+1].split(': ')[1].trim());

$('#arma1').val(inputs[23+1].split(': ')[1].trim());
$('#arma2').val(inputs[24+1].split(': ')[1].trim());
$('#arma3').val(inputs[25+1].split(': ')[1].trim());
$('#arma4').val(inputs[26+1].split(': ')[1].trim());
$('#arma5').val(inputs[27+1].split(': ')[1].trim());
$('#arma6').val(inputs[28+1].split(': ')[1].trim());
$('#arma7').val(inputs[29+1].split(': ')[1].trim());
$('#arma8').val(inputs[30+1].split(': ')[1].trim());

$('#arma11').val(inputs[31+1].split(': ')[1].trim());
$('#arma12').val(inputs[32+1].split(': ')[1].trim());
$('#arma13').val(inputs[33+1].split(': ')[1].trim());
$('#arma14').val(inputs[34+1].split(': ')[1].trim());
$('#arma15').val(inputs[35+1].split(': ')[1].trim());
$('#arma16').val(inputs[36+1].split(': ')[1].trim());
$('#arma17').val(inputs[37+1].split(': ')[1].trim());
$('#arma18').val(inputs[38+1].split(': ')[1].trim());

$('#arma21').val(inputs[39+1].split(': ')[1].trim());
$('#arma22').val(inputs[40+1].split(': ')[1].trim());
$('#arma23').val(inputs[41+1].split(': ')[1].trim());
$('#arma24').val(inputs[42+1].split(': ')[1].trim());
$('#arma25').val(inputs[43+1].split(': ')[1].trim());
$('#arma26').val(inputs[44+1].split(': ')[1].trim());
$('#arma27').val(inputs[45+1].split(': ')[1].trim());
$('#arma28').val(inputs[46+1].split(': ')[1].trim());

$('#arma31').val(inputs[47+1].split(': ')[1].trim());
$('#arma32').val(inputs[48+1].split(': ')[1].trim());
$('#arma33').val(inputs[49+1].split(': ')[1].trim());
$('#arma34').val(inputs[50+1].split(': ')[1].trim());
$('#arma35').val(inputs[51+1].split(': ')[1].trim());
$('#arma36').val(inputs[52+1].split(': ')[1].trim());
$('#arma37').val(inputs[53+1].split(': ')[1].trim());
$('#arma38').val(inputs[54+1].split(': ')[1].trim());

$('#vantagens1').val(inputs[55+1].split(': ')[1].trim());
$('#vantagens2').val(inputs[56+1].split(': ')[1].trim());
$('#vantagens3').val(inputs[57+1].split(': ')[1].trim());
$('#vantagens4').val(inputs[58+1].split(': ')[1].trim());
$('#vantagens5').val(inputs[59+1].split(': ')[1].trim());
$('#vantagens6').val(inputs[60+1].split(': ')[1].trim());
$('#vantagens7').val(inputs[61+1].split(': ')[1].trim());
$('#vantagens8').val(inputs[62+1].split(': ')[1].trim());
$('#vantagens9').val(inputs[63+1].split(': ')[1].trim());
$('#vantagens10').val(inputs[64+1].split(': ')[1].trim());
$('#vantagens11').val(inputs[65+1].split(': ')[1].trim());
$('#vantagens12').val(inputs[66+1].split(': ')[1].trim());
$('#vantagens13').val(inputs[67+1].split(': ')[1].trim());
$('#vantagens14').val(inputs[68+1].split(': ')[1].trim());
$('#vantagens15').val(inputs[69+1].split(': ')[1].trim());
$('#vantagens16').val(inputs[70+1].split(': ')[1].trim());
$('#vantagens17').val(inputs[71+1].split(': ')[1].trim());
$('#vantagens18').val(inputs[72+1].split(': ')[1].trim());
$('#vantagens19').val(inputs[73+1].split(': ')[1].trim());
$('#vantagens20').val(inputs[74+1].split(': ')[1].trim());

$('#desvantagens1').val(inputs[75+1].split(': ')[1].trim());
$('#desvantagens2').val(inputs[76+1].split(': ')[1].trim());
$('#desvantagens3').val(inputs[77+1].split(': ')[1].trim());
$('#desvantagens4').val(inputs[78+1].split(': ')[1].trim());
$('#desvantagens5').val(inputs[79+1].split(': ')[1].trim());
$('#desvantagens6').val(inputs[80+1].split(': ')[1].trim());
$('#desvantagens7').val(inputs[81+1].split(': ')[1].trim());
$('#desvantagens8').val(inputs[82+1].split(': ')[1].trim());
$('#desvantagens9').val(inputs[83+1].split(': ')[1].trim());
$('#desvantagens10').val(inputs[84+1].split(': ')[1].trim());
$('#desvantagens11').val(inputs[85+1].split(': ')[1].trim());
$('#desvantagens12').val(inputs[86+1].split(': ')[1].trim());
$('#desvantagens13').val(inputs[87+1].split(': ')[1].trim());
$('#desvantagens14').val(inputs[88+1].split(': ')[1].trim());
$('#desvantagens15').val(inputs[89+1].split(': ')[1].trim());
$('#desvantagens16').val(inputs[90+1].split(': ')[1].trim());
$('#desvantagens17').val(inputs[91+1].split(': ')[1].trim());
$('#desvantagens18').val(inputs[92+1].split(': ')[1].trim());
$('#desvantagens19').val(inputs[93+1].split(': ')[1].trim());
$('#desvantagens20').val(inputs[94+1].split(': ')[1].trim());

$('#skills1').val(inputs[95+1].split(': ')[1].trim());
$('#skills2').val(inputs[96+1].split(': ')[1].trim());
$('#skills3').val(inputs[97+1].split(': ')[1].trim());
$('#skills4').val(inputs[98+1].split(': ')[1].trim());
$('#skills5').val(inputs[99+1].split(': ')[1].trim());
$('#skills6').val(inputs[100+1].split(': ')[1].trim());
$('#skills7').val(inputs[101+1].split(': ')[1].trim());
$('#skills8').val(inputs[102+1].split(': ')[1].trim());
$('#skills9').val(inputs[103+1].split(': ')[1].trim());
$('#skills10').val(inputs[104+1].split(': ')[1].trim());
$('#skills11').val(inputs[105+1].split(': ')[1].trim());
$('#skills12').val(inputs[106+1].split(': ')[1].trim());
$('#skills13').val(inputs[107+1].split(': ')[1].trim());
$('#skills14').val(inputs[108+1].split(': ')[1].trim());
$('#skills15').val(inputs[109+1].split(': ')[1].trim());
$('#skills16').val(inputs[110+1].split(': ')[1].trim());
$('#skills17').val(inputs[111+1].split(': ')[1].trim());
$('#skills18').val(inputs[112+1].split(': ')[1].trim());
$('#skills19').val(inputs[113+1].split(': ')[1].trim());
$('#skills20').val(inputs[114+1].split(': ')[1].trim());
$('#skills21').val(inputs[115+1].split(': ')[1].trim());
$('#skills22').val(inputs[116+1].split(': ')[1].trim());
$('#skills23').val(inputs[117+1].split(': ')[1].trim());
$('#skills24').val(inputs[118+1].split(': ')[1].trim());
$('#skills25').val(inputs[119+1].split(': ')[1].trim());
$('#skills26').val(inputs[120+1].split(': ')[1].trim());
$('#skills27').val(inputs[121+1].split(': ')[1].trim());
$('#skills28').val(inputs[122+1].split(': ')[1].trim());
$('#skills29').val(inputs[123+1].split(': ')[1].trim());
$('#skills30').val(inputs[124+1].split(': ')[1].trim());
$('#skills31').val(inputs[125+1].split(': ')[1].trim());
$('#skills32').val(inputs[126+1].split(': ')[1].trim());
$('#skills33').val(inputs[127+1].split(': ')[1].trim());
$('#skills34').val(inputs[128+1].split(': ')[1].trim());
$('#skills35').val(inputs[129+1].split(': ')[1].trim());
$('#skills36').val(inputs[130+1].split(': ')[1].trim());
$('#skills37').val(inputs[131+1].split(': ')[1].trim());
$('#skills38').val(inputs[132+1].split(': ')[1].trim());
$('#skills39').val(inputs[133+1].split(': ')[1].trim());
$('#skills40').val(inputs[134+1].split(': ')[1].trim());

$('#skillsx1').val(inputs[135+1].split(': ')[1].trim());
$('#skillsx2').val(inputs[136+1].split(': ')[1].trim());
$('#skillsx3').val(inputs[137+1].split(': ')[1].trim());
$('#skillsx4').val(inputs[138+1].split(': ')[1].trim());
$('#skillsx5').val(inputs[139+1].split(': ')[1].trim());
$('#skillsx6').val(inputs[140+1].split(': ')[1].trim());
$('#skillsx7').val(inputs[141+1].split(': ')[1].trim());
$('#skillsx8').val(inputs[142+1].split(': ')[1].trim());
$('#skillsx9').val(inputs[143+1].split(': ')[1].trim());
$('#skillsx10').val(inputs[144+1].split(': ')[1].trim());
$('#skillsx11').val(inputs[145+1].split(': ')[1].trim());
$('#skillsx12').val(inputs[146+1].split(': ')[1].trim());
$('#skillsx13').val(inputs[147+1].split(': ')[1].trim());
$('#skillsx14').val(inputs[148+1].split(': ')[1].trim());
$('#skillsx15').val(inputs[149+1].split(': ')[1].trim());
$('#skillsx16').val(inputs[150+1].split(': ')[1].trim());
$('#skillsx17').val(inputs[151+1].split(': ')[1].trim());
$('#skillsx18').val(inputs[152+1].split(': ')[1].trim());
$('#skillsx19').val(inputs[153+1].split(': ')[1].trim());
$('#skillsx20').val(inputs[154+1].split(': ')[1].trim());
$('#skillsx21').val(inputs[155+1].split(': ')[1].trim());
$('#skillsx22').val(inputs[156+1].split(': ')[1].trim());
$('#skillsx23').val(inputs[157+1].split(': ')[1].trim());
$('#skillsx24').val(inputs[158+1].split(': ')[1].trim());
$('#skillsx25').val(inputs[159+1].split(': ')[1].trim());
$('#skillsx26').val(inputs[160+1].split(': ')[1].trim());
$('#skillsx27').val(inputs[161+1].split(': ')[1].trim());
$('#skillsx28').val(inputs[162+1].split(': ')[1].trim());
$('#skillsx29').val(inputs[163+1].split(': ')[1].trim());
$('#skillsx30').val(inputs[164+1].split(': ')[1].trim());
$('#skillsx31').val(inputs[165+1].split(': ')[1].trim());
$('#skillsx32').val(inputs[166+1].split(': ')[1].trim());
$('#skillsx33').val(inputs[167+1].split(': ')[1].trim());
$('#skillsx34').val(inputs[168+1].split(': ')[1].trim());
$('#skillsx35').val(inputs[169+1].split(': ')[1].trim());
$('#skillsx36').val(inputs[170+1].split(': ')[1].trim());
$('#skillsx37').val(inputs[171+1].split(': ')[1].trim());
$('#skillsx38').val(inputs[172+1].split(': ')[1].trim());
$('#skillsx39').val(inputs[173+1].split(': ')[1].trim());
$('#skillsx40').val(inputs[174+1].split(': ')[1].trim());

$('#skillsxx1').val(inputs[175+1].split(': ')[1].trim());
$('#skillsxx2').val(inputs[176+1].split(': ')[1].trim());
$('#skillsxx3').val(inputs[177+1].split(': ')[1].trim());
$('#skillsxx4').val(inputs[178+1].split(': ')[1].trim());
$('#skillsxx5').val(inputs[179+1].split(': ')[1].trim());
$('#skillsxx6').val(inputs[180+1].split(': ')[1].trim());
$('#skillsxx7').val(inputs[181+1].split(': ')[1].trim());
$('#skillsxx8').val(inputs[182+1].split(': ')[1].trim());
$('#skillsxx9').val(inputs[183+1].split(': ')[1].trim());
$('#skillsxx10').val(inputs[184+1].split(': ')[1].trim());
$('#skillsxx11').val(inputs[185+1].split(': ')[1].trim());
$('#skillsxx12').val(inputs[186+1].split(': ')[1].trim());
$('#skillsxx13').val(inputs[187+1].split(': ')[1].trim());
$('#skillsxx14').val(inputs[188+1].split(': ')[1].trim());
$('#skillsxx15').val(inputs[189+1].split(': ')[1].trim());
$('#skillsxx16').val(inputs[190+1].split(': ')[1].trim());
$('#skillsxx17').val(inputs[191+1].split(': ')[1].trim());
$('#skillsxx18').val(inputs[192+1].split(': ')[1].trim());
$('#skillsxx19').val(inputs[193+1].split(': ')[1].trim());
$('#skillsxx20').val(inputs[194+1].split(': ')[1].trim());
$('#skillsxx21').val(inputs[195+1].split(': ')[1].trim());
$('#skillsxx22').val(inputs[196+1].split(': ')[1].trim());
$('#skillsxx23').val(inputs[197+1].split(': ')[1].trim());
$('#skillsxx24').val(inputs[198+1].split(': ')[1].trim());
$('#skillsxx25').val(inputs[199+1].split(': ')[1].trim());
$('#skillsxx26').val(inputs[200+1].split(': ')[1].trim());
$('#skillsxx27').val(inputs[201+1].split(': ')[1].trim());
$('#skillsxx28').val(inputs[202+1].split(': ')[1].trim());
$('#skillsxx29').val(inputs[203+1].split(': ')[1].trim());
$('#skillsxx30').val(inputs[204+1].split(': ')[1].trim());
$('#skillsxx31').val(inputs[205+1].split(': ')[1].trim());
$('#skillsxx32').val(inputs[206+1].split(': ')[1].trim());
$('#skillsxx33').val(inputs[207+1].split(': ')[1].trim());
$('#skillsxx34').val(inputs[208+1].split(': ')[1].trim());
$('#skillsxx35').val(inputs[209+1].split(': ')[1].trim());
$('#skillsxx36').val(inputs[210+1].split(': ')[1].trim());
$('#skillsxx37').val(inputs[211+1].split(': ')[1].trim());
$('#skillsxx38').val(inputs[212+1].split(': ')[1].trim());
$('#skillsxx39').val(inputs[213+1].split(': ')[1].trim());
$('#skillsxx40').val(inputs[214+1].split(': ')[1].trim());

$('#textarea1').val(inputs[215+1].split(': ')[1].trim());

    };
    leitor.readAsText(arquivo);
  });
});